context.properties = {
    default.clock.rate = 48000
    default.clock.quantum = 4096
    default.clock.min-quantum = 2048
    default.clock.max-quantum = 8192
}

context.modules = [
    {
        name = libpipewire-module-protocol-pulse
        args = {
            pulse.min.req = 4096/48000
            pulse.min.quantum = 4096/48000
            pulse.default.req = 4096/48000
            pulse.default.quantum = 4096/48000
            pulse.max.req = 8192/48000
            pulse.max.quantum = 8192/48000
        }
    }
]
