[General]
x=0
y=1440

[caching]
lastCacheFileHash=@ByteArray(4cd31df026fd82243805a326dc0cafd7383f7e3d30c9413e7044d507aae281e2)
lastDownloadSHA256=@ByteArray(7a49cd99423f561e681e9d32071ec05d06beca5a9224972a4a4c99d684deec04)
lastFileName=/home/vib1240n/.cache/Raspberry Pi/Raspberry Pi Imager/lastdownload.cache

[imagecustomization]
capitalCity="Washington, D.C. (United States)"
hostname=kitcheye-pi
keyboard=us
recommendedWifiCountry=US
sshAuthorizedKeys=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILW4DecEWKaUsjbw7RYN3SLaxq9gMslQap1AEc2p0xev msi-archy\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFncHthpaQcx6SJgmUePULOS+QrKEZONoRTpudfW97jY vibhorsgr@gmail.com
sshEnabled=true
sshPasswordAuth=false
sshUserName=vib1240n
sshUserPassword=$y$jB5$n7nPtZLKhZIPs3aEuV4Rt.$8fvi3cEPa7Dvg1Bwvn8yLxKZTWJ9uXxk7tRRlgNMgZ4
timezone=America/Los_Angeles
wifiHidden=false
wifiMode=secure
wifiPasswordCrypt=171c95a92f138f69ec10ec727b26fa0a4364ebdaba196633b2dd9ce083714fe6
wifiSSID=Naboo
