[Nextcloud]
type = webdav
url = https://cloud.vibhoresagar.dev/remote.php/dav/files/me@vibhoresagar.dev/
vendor = nextcloud
user = me@vibhoresagar.dev
pass = cFOgHRUSBSgUHPtVV5-3W0YRFII-1rMnlTDv-KWV1VSa73SS0ySssscT9_Fd

