# Wallpaper (placeholder - will fix later)
bind = SUPER CTRL ALT SHIFT, W, exec, notify-send "Wallpaper" "Use Nucleus menu for now"

# Clipboard (nucleus native or rofi)
bind = SUPER CTRL ALT SHIFT, O, exec, ~/.config/rofi/scripts/clipboard.sh

# Screenshots
bind = SUPER SHIFT, 3, exec, ~/.config/hypr/scripts/Screenshot.sh full
bind = SUPER SHIFT, 4, exec, ~/.config/hypr/scripts/Screenshot.sh area

# Powermenu (nucleus native)
# bind = SUPER, P, exec, qs -c nucleus-shell ipc call powermenu toggle

# Audio switcher
bind = ALT, a, exec, rofi -show audio -modi "audio:~/.config/rofi/scripts/audio-output-mode.sh" -theme ~/.config/rofi/audio-menu.rasi
