# Wallpaper (placeholder - will fix later)
bind = SUPER CTRL ALT SHIFT, W, exec, ~/.config/hypr/scripts/NucleusWallpaper.sh

# Clipboard (nucleus native or rofi)
bind = SUPER CTRL ALT SHIFT, O, exec, ~/.config/rofi/scripts/clipboard.sh

# Screenshots
bind = SUPER SHIFT, 3, exec, ~/.config/hypr/scripts/Screenshot.sh full
bind = SUPER SHIFT, 4, exec, ~/.config/hypr/scripts/Screenshot.sh area

# Powermenu (nucleus native)
# bind = SUPER, P, exec, qs -c nucleus-shell ipc call powermenu toggle

# Audio switcher
bind = ALT, a, exec, rofi -show audio -modi "audio:~/.config/rofi/scripts/audio-output-mode.sh" -theme ~/.config/rofi/audio-menu.rasi

# media 
bindl = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/volume-nucleus.sh up
bindl = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume-nucleus.sh down
bindl = , XF86AudioMute, exec, ~/.config/hypr/scripts/volume-nucleus.sh mute
bindl = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/Brightness.sh up
bindl = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/Brightness.sh down
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous

