# Window focus (HYPER + HJKL)
bind = SUPER CTRL ALT SHIFT, H, movefocus, l
bind = SUPER CTRL ALT SHIFT, J, movefocus, d
bind = SUPER CTRL ALT SHIFT, K, movefocus, u
bind = SUPER CTRL ALT SHIFT, L, movefocus, r

# Window swap (MEH + HJKL)
bind = CTRL ALT SHIFT, H, swapwindow, l
bind = CTRL ALT SHIFT, J, swapwindow, d
bind = CTRL ALT SHIFT, K, swapwindow, u
bind = CTRL ALT SHIFT, L, swapwindow, r

# Workspaces (HYPER + number)
bind = SUPER CTRL ALT SHIFT, 1, workspace, 1
bind = SUPER CTRL ALT SHIFT, 2, workspace, 2
bind = SUPER CTRL ALT SHIFT, 3, workspace, 3
bind = SUPER CTRL ALT SHIFT, 4, workspace, 4
bind = SUPER CTRL ALT SHIFT, 5, workspace, 5
bind = SUPER CTRL ALT SHIFT, 6, workspace, 6
bind = SUPER CTRL ALT SHIFT, 7, workspace, 7
bind = SUPER CTRL ALT SHIFT, 8, workspace, 8

# Move to workspace (MEH + number)
bind = CTRL ALT SHIFT, 1, movetoworkspace, 1
bind = CTRL ALT SHIFT, 2, movetoworkspace, 2
bind = CTRL ALT SHIFT, 3, movetoworkspace, 3
bind = CTRL ALT SHIFT, 4, movetoworkspace, 4
bind = CTRL ALT SHIFT, 5, movetoworkspace, 5
bind = CTRL ALT SHIFT, 6, movetoworkspace, 6
bind = CTRL ALT SHIFT, 7, movetoworkspace, 7
bind = CTRL ALT SHIFT, 8, movetoworkspace, 8

# Window actions
bind = SUPER CTRL ALT SHIFT, Q, killactive
bind = SUPER CTRL ALT SHIFT, M, fullscreen, 1
bind = CTRL ALT SHIFT, F, togglefloating

# Resize mode
bind = SUPER CTRL ALT SHIFT, R, submap, resize
submap = resize
binde = , H, resizeactive, -50 0
binde = , J, resizeactive, 0 50
binde = , K, resizeactive, 0 -50
binde = , L, resizeactive, 50 0
bind = , escape, submap, reset
bind = , return, submap, reset
submap = reset

# Apps (HYPER)
bind = SUPER CTRL ALT SHIFT, T, exec, kitty
bind = SUPER CTRL ALT SHIFT, B, exec, zen-browser
bind = SUPER CTRL ALT SHIFT, Z, exec, zed
bind = SUPER CTRL ALT SHIFT, D, exec, vesktop
bind = SUPER CTRL ALT SHIFT, Return, exec, nemo

# Launcher
bind = SUPER, space, exec, ~/.config/rofi/scripts/launcher.sh

# Special workspace
bind = SUPER CTRL ALT SHIFT, U, togglespecialworkspace
bind = CTRL ALT SHIFT, U, movetoworkspace, special

# Layout
bind = SUPER CTRL ALT SHIFT, Y, exec, ~/.config/hypr/scripts/toggle-layout.sh

# Mouse
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Media

# Lock
bind = SUPER, L, exec, hyprlock & sleep 0.2
bind = CTRL, L, exec, systemctl suspend
bind = ALT SHIFT, L, exec, systemctl hibernate

# Shell toggle
bind = SUPER SHIFT, S, exec, ~/.config/hypr/scripts/shell-toggle.sh

# special
bind = SUPER CTRL ALT SHIFT, BackSpace, exec, ~/Development/bash_scripts/toggle-caffeinate.sh
